### ISSUE TITLE
Chirp developer account credintials

### ISSUE THREAD

**Issue by FajarKhan** [ssindher11/ChirpTut#1]
Hi, 

I am not able to find any credentials in their dev portal. could you please help me with it?
Seems like they have changed the website completely.

**Comment by ssindher11** [comment]
> Hi, 
> 
> I am not able to find any credentials in their dev portal. could you please help me with it?
> Seems like they have changed the website completely.

Hey

So the thing is, now Chirp has been acquired by Sonos. And so, new credentials are not possible.

**Comment by FajarKhan** [comment]
that hurts!! 
so old credentials still work right?  is there any possible way we can implement this in android right now?

**Comment by ssindher11** [comment]
The old credentials will still work. You can probably look for alternate libraries to implement this.
